apiVersion: v1
kind: Service
metadata:
  namespace: user-service
  labels:
    app: user-service
  name: user-service
spec:
  ports:
  
    - protocol: TCP
      port: 3580
      targetPort: 3580
   
   
    - protocol: TCP
      port: 25500
      targetPort: 25500
   
  selector:
    app: user-service
  type: ClusterIP
